# Generated by Django 6.0.7 on 2026-07-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'subcategories'},
        ),
    ]
