# Generated by Django 6.0.7 on 2026-07-10 14:15

import django.db.models.deletion
from django.db import migrations, models

# Backfill legs on the rows seeded before accounts existed: every pre-v2
# transaction is an income or expense, so point its single leg at the default
# everyday account (Main Checking, id=1). Income lands in it; expense leaves it.
# Must run BEFORE the CHECK constraints, or the all-NULL rows would fail
# tx_at_least_one_account.
BACKFILL_SQL = """
UPDATE transactions_transaction
SET destination_account_id = 1
WHERE subcategory_id IN (
    SELECT s.id FROM transactions_subcategory s
    JOIN transactions_category c ON c.id = s.category_id
    WHERE c.kind = 'income'
);
UPDATE transactions_transaction
SET source_account_id = 1
WHERE subcategory_id IN (
    SELECT s.id FROM transactions_subcategory s
    JOIN transactions_category c ON c.id = s.category_id
    WHERE c.kind = 'expense'
);
"""

BACKFILL_REVERSE_SQL = """
UPDATE transactions_transaction
SET source_account_id = NULL, destination_account_id = NULL;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_category_options_alter_subcategory_options'),
        ('wallets', '0002_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='wallets.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='wallets.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.subcategory'),
        ),
        migrations.RunSQL(BACKFILL_SQL, reverse_sql=BACKFILL_REVERSE_SQL),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('source_account__isnull', False), ('destination_account__isnull', False), _connector='OR'), name='tx_at_least_one_account'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('source_account', models.F('destination_account')), _negated=True), name='tx_no_self_transfer'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='tx_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_account__isnull', False), ('destination_account__isnull', False), ('subcategory__isnull', True)), models.Q(models.Q(('source_account__isnull', False), ('destination_account__isnull', False), _negated=True), ('subcategory__isnull', False)), _connector='OR'), name='tx_subcategory_iff_not_transfer'),
        ),
    ]
