# Generated by Django 6.0.7 on 2026-07-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_seed_liability_activity'),
        ('wallets', '0005_seed_liabilities'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='tx_subcategory_iff_not_transfer',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_account__isnull', False), ('destination_account__isnull', False)), ('subcategory__isnull', False), _connector='OR'), name='tx_subcategory_required_for_non_transfer'),
        ),
    ]
