# Generated by Django 6.0.7 on 2026-07-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_transaction_tx_subcategory_iff_not_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, db_default='', max_length=255),
        ),
    ]
