"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Config is env-driven so the same image runs in dev (defaults below) and prod
# (values injected via docker-compose.prod.yml / .env.prod). See the deployment
# checklist: https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: set SECRET_KEY from the environment in production. The literal
# fallback is for local dev only.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-$239kks%uy*-dj-l-9+s=77fp9r6_is%o6e)(f&b_xr^0htvs&",
)

# SECURITY WARNING: never run with DEBUG on in production. Defaults on for dev;
# docker-compose.prod.yml sets DEBUG=False.
DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

# Comma-separated list, e.g. "example.com,www.example.com". Required when DEBUG
# is off; under DEBUG Django already allows localhost.
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", "").split(",") if h.strip()
]

# Origins trusted for unsafe (CSRF-protected) requests — must include scheme,
# e.g. "https://example.com". Needed once served from a real domain.
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# HTTPS posture, decoupled from DEBUG. When on: cookies are Secure (HTTPS-only)
# and HTTPS hardening applies. Defaults on in production, off in dev. Set
# SECURE_COOKIES=False if you MUST serve over plain HTTP (no TLS) — cookies then
# work over HTTP but traffic (including the JWT) is unencrypted. Prefer HTTPS.
SECURE_COOKIES = os.environ.get("SECURE_COOKIES", str(not DEBUG)).lower() == "true"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "authn",
    "wallets",
    "transactions",
    "reports",
    "budgets",
]

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "EXCEPTION_HANDLER": "config.api.api_exception_handler",
    # JWT carried in an httpOnly cookie; every endpoint requires auth by default
    # (login/refresh and the docs opt back out explicitly).
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "authn.authentication.CookieJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Per-IP rate limit for the login endpoint (brute-force defense). Applied only
    # where a view opts in via `throttle_scope` — not global. Uses the default
    # cache; with multiple gunicorn workers use a shared cache (Redis) for an
    # exact limit rather than per-worker.
    "DEFAULT_THROTTLE_RATES": {
        "login": "5/min",
    },
    # Number of trusted reverse proxies in front of the app. Set to 1 in prod (via
    # env) so throttling keys off the real client IP from X-Forwarded-For and
    # can't be spoofed. None (dev / no proxy) → uses REMOTE_ADDR.
    "NUM_PROXIES": int(os.environ["NUM_PROXIES"])
    if os.environ.get("NUM_PROXIES")
    else None,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Home Budget Planner API",
    "DESCRIPTION": (
        "REST API for accounts, purposes, categories, and transactions. "
        "A transaction's type (income / expense / transfer) is derived from which "
        "account legs are set; see the transactions endpoint for details."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Serve Swagger UI / ReDoc assets from the bundled sidecar (django static
    # files) instead of an external CDN, so the docs render in offline / Docker /
    # air-gapped environments and aren't pinned to a drifting "@latest" build.
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    # Section order in Swagger UI / ReDoc. Declaring the tags at the schema root
    # fixes their display order (health first, reports last); any tag not listed
    # here would be appended after these.
    "TAGS": [
        {"name": "health", "description": "Liveness / readiness probe (public)."},
        {"name": "auth", "description": "Cookie-based JWT authentication."},
        {
            "name": "accounts",
            "description": "Money containers — assets and liabilities.",
        },
        {
            "name": "purposes",
            "description": "Savings goals accounts can be earmarked toward.",
        },
        {"name": "categories", "description": "Income / expense classification."},
        {"name": "subcategories", "description": "Subdivisions of a category."},
        {
            "name": "transactions",
            "description": "Money movements (income / expense / transfer).",
        },
        {
            "name": "budget-plans",
            "description": "Planned spending / income for a period.",
        },
        {"name": "reports", "description": "Read-only aggregations for dashboards."},
    ],
}

# --- JWT authentication --------------------------------------------------------
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # Rotate the refresh token on every refresh and blacklist the old one, so a
    # leaked refresh token has a short useful life and logout can revoke it.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# Cookie carrying the JWTs. httpOnly keeps them unreadable from JavaScript (XSS
# defense); the CSRF token below covers the risk cookies reintroduce. `Secure`
# tracks SECURE_COOKIES so the cookies work over plain HTTP when that's off.
AUTH_COOKIE = {
    "ACCESS_NAME": "access_token",
    "REFRESH_NAME": "refresh_token",
    "HTTPONLY": True,
    "SECURE": SECURE_COOKIES,
    "SAMESITE": "Lax",
    "PATH": "/",
}

# CSRF: the token cookie must stay readable by JS (double-submit), so it is NOT
# httpOnly. Clients send it back in the X-CSRFToken header on unsafe requests.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = SECURE_COOKIES

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves collected static files (admin, Swagger sidecar) in production, where
    # runserver's dev static serving is off. No-op behind runserver in dev.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# PostgreSQL when POSTGRES_DB is set (the Docker setup does this — see
# docker-compose.yml); otherwise SQLite, so local `manage.py` works without a
# running Postgres.

if os.environ.get("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["POSTGRES_DB"],
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "db"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# `collectstatic` gathers admin + Swagger-sidecar assets here; WhiteNoise serves
# them in production.
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
}
if not DEBUG:
    # Compress + serve with far-future cache headers in production.
    STORAGES["staticfiles"]["BACKEND"] = (
        "whitenoise.storage.CompressedStaticFilesStorage"
    )


# HTTPS hardening — active whenever the site is served over HTTPS (SECURE_COOKIES),
# independent of DEBUG. Assumes a TLS-terminating reverse proxy in front: trust its
# X-Forwarded-Proto so Django knows requests are HTTPS.
if SECURE_COOKIES:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    # Opt-in extras (set via env). SSL redirect is usually the proxy's job; HSTS
    # locks browsers to HTTPS so enable it only once HTTPS is stable.
    SECURE_SSL_REDIRECT = (
        os.environ.get("SECURE_SSL_REDIRECT", "False").lower() == "true"
    )
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
    SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
