# Generated by Django 6.0.7 on 2026-07-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_reset_sequences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('investment', 'Investment'), ('liability', 'Liability')], max_length=10),
        ),
    ]
