# Generated by Django 6.0.7 on 2026-08-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_seed_liabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='purpose',
            name='is_off_budget',
            field=models.BooleanField(default=False),
        ),
    ]
