# Generated by Django 6.0.7 on 2026-08-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_purpose_is_off_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='is_off_budget',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
