apiVersion: v1
kind: ConfigMap
metadata:
  name: hbp-configmap
  namespace: hbp
data:
  DB_NAME: hbp
  DB_USER: hbp
  ADMIN_USER: admin
  ADMIN_EMAIL: admin@example.com
  API_PROXY_TARGET: http://hbp-web:8000
