apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbp-db
  namespace: hbp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbp-db
  template:
    metadata:
      labels:
        app: hbp-db
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: hbp-configmap
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: hbp-configmap
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hbp-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql
      volumes:
        - name: postgres-storage
          emptyDir: {}
