apiVersion: v1
kind: Service
metadata:
  name: hbp-frontend
  namespace: hbp
spec:
  selector:
    app: hbp-frontend
  # type: LoadBalancer # for cloud providers that support it
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
