apiVersion: v1
kind: Service
metadata:
  name: hbp-frontend
  namespace: hbp
spec:
  selector:
    app: hbp-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbp-frontend
  namespace: hbp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbp-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hbp-frontend
    spec:
      containers:
      - name: hbp-frontend
        image: ghcr.io/mcesarczyk/home-budget-planner-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: API_PROXY_TARGET
          valueFrom:
            configMapKeyRef:
              name: hbp-configmap
              key: API_PROXY_TARGET
