# Generated by Django 6.0.7 on 2026-07-31 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0010_transaction_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='transactions.subcategory')),
                ('budget_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.budgetplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('budget_plan', 'subcategory'), name='uq_budget_item_per_subcategory'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='budget_item_amount_positive')],
            },
        ),
    ]
