---

name: Detect Secrets & Passwords

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-detect-secrets:
    name: Call Detect Secrets
    uses: MCesarczyk/actions/.github/workflows/detect-secrets.yaml@main
    permissions:
      pull-requests: write
      contents: read
